In [1]:
import os
import pandas as pd
import numpy as np

# Define the folder containing the dataset
dataset_folder = "keypoints"

# Define the label map
label_map = {'frez': 0, 'hurry': 1, 'listen': 2, 'stop': 3, 'hostage': 4, 'understand': 5, 'pistol': 6, 'come': 7}  # Add more labels as needed

# Initialize arrays
labels = []
data = []

# Function to check for NaNs in a DataFrame
def contains_nan(df):
    return df.isnull().values.any()

# Iterate through each folder in the dataset directory
for folder_name in os.listdir(dataset_folder):
    folder_path = os.path.join(dataset_folder, folder_name)
    
    # Check if it's a directory
    if os.path.isdir(folder_path):
        # Extract label from folder name using label_map
        label = label_map.get(folder_name, None)
        if label is None:
            continue
        
        # Iterate through each CSV file in the folder
        for filename in os.listdir(folder_path):
            file_path = os.path.join(folder_path, filename)
            # Read CSV file
            df = pd.read_csv(file_path)
            # Check for NaNs
            if contains_nan(df):
                print(f'NaN values found in file: {file_path}')
            # Flatten the data and append to the data array
            file_data = df.values
            # Append the file data to the list
            data.append(file_data)
            labels.append(label)  # Append the label

# Convert data and labels to numpy arrays for further processing if needed
data = np.array(data)
labels = np.array(labels)


In [ ]:
# import os
# import pandas as pd

# # Define the root directory containing the folders and CSV files
# root_directory = 'keypoints'

# # List of columns to be deleted
# columns_to_delete = ['class_label', 'pose_keypoint_1_x', 'pose_keypoint_1_y', 'pose_keypoint_1_z', 'pose_keypoint_3_x', 'pose_keypoint_3_y', 'pose_keypoint_3_z', 'pose_keypoint_4_x', 'pose_keypoint_4_y', 'pose_keypoint_4_z', 'pose_keypoint_6_x', 'pose_keypoint_6_y', 'pose_keypoint_6_z', 'pose_keypoint_14_x', 'pose_keypoint_14_y', 'pose_keypoint_14_z', 'pose_keypoint_16_x', 'pose_keypoint_16_y', 'pose_keypoint_16_z', 'pose_keypoint_18_x', 'pose_keypoint_18_y', 'pose_keypoint_18_z', 'pose_keypoint_20_x', 'pose_keypoint_20_y', 'pose_keypoint_20_z', 'pose_keypoint_22_x', 'pose_keypoint_22_y', 'pose_keypoint_22_z', 'pose_keypoint_25_x', 'pose_keypoint_25_y', 'pose_keypoint_25_z', 'pose_keypoint_26_x', 'pose_keypoint_26_y', 'pose_keypoint_26_z', 'pose_keypoint_27_x', 'pose_keypoint_27_y', 'pose_keypoint_27_z', 'pose_keypoint_28_x', 'pose_keypoint_28_y', 'pose_keypoint_28_z', 'pose_keypoint_29_x', 'pose_keypoint_29_y', 'pose_keypoint_29_z', 'pose_keypoint_30_x', 'pose_keypoint_30_y', 'pose_keypoint_30_z', 'pose_keypoint_31_x', 'pose_keypoint_31_y', 'pose_keypoint_31_z', 'pose_keypoint_32_x', 'pose_keypoint_32_y', 'pose_keypoint_32_z']  # Replace with your column names

# # Function to delete specified columns from a DataFrame
# def delete_columns(df, columns):
#     return df.drop(columns=columns, errors='ignore')

# # Function to process CSV files in the directory and subdirectories
# def process_csv_files(directory, columns_to_delete):
#     for foldername, subfolders, filenames in os.walk(directory):
#         for filename in filenames:
#             if filename.endswith('.csv'):
#                 file_path = os.path.join(foldername, filename)
#                 try:
#                     df = pd.read_csv(file_path)
#                     # Delete the specified columns
#                     df = delete_columns(df, columns_to_delete)
#                     # Save the modified DataFrame back to CSV
#                     df.to_csv(file_path, index=False)
#                     print(f'Processed file: {file_path}')
#                 except Exception as e:
#                     print(f'Error processing file {file_path}: {e}')

# # Run the function
# process_csv_files(root_directory, columns_to_delete)


In [ ]:
# import os
# import pandas as pd

# # Define the root directory containing the folders and CSV files
# root_directory = 'keypoints'

# # Function to check for null values in a DataFrame
# def contains_nan(df):
#     return df.isnull().values.any()

# # Function to find CSV files with null values
# def find_null_in_csv_files(directory):
#     for foldername, subfolders, filenames in os.walk(directory):
#         for filename in filenames:
#             if filename.endswith('.csv'):
#                 file_path = os.path.join(foldername, filename)
#                 try:
#                     df = pd.read_csv(file_path)
#                     if contains_nan(df):
#                         print(f'NaN values found in file: {file_path}')
#                 except Exception as e:
#                     print(f'Error processing file {file_path}: {e}')

# # Run the function
# find_null_in_csv_files(root_directory)


In [ ]:
# import pandas as pd

# # Define the path to the CSV file
# file_path = 'keypoints\\hurry\\4.csv'

# # Read the CSV file into a DataFrame
# df = pd.read_csv(file_path)

# # Check for null values in each row
# null_rows = df[df.isnull().any(axis=1)]

# # Print the indices and the rows with null values
# for index, row in null_rows.iterrows():
#     print(f'Null value found in row {index + 1}:')
#     print(row)
#     print('\n')


In [2]:
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
# Convert data and labels to numpy arrays
X = np.array(data)
y = to_categorical(labels).astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [3]:
# Ensure there are no NaNs or infinite values in the input data and labels
print(f'NaNs in X_train: {np.isnan(X_train).sum()}')
print(f'NaNs in y_train: {np.isnan(y_train).sum()}')
print(f'Infs in X_train: {np.isinf(X_train).sum()}')
print(f'Infs in y_train: {np.isinf(y_train).sum()}')

print(f'NaNs in X_test: {np.isnan(X_test).sum()}')
print(f'NaNs in y_test: {np.isnan(y_test).sum()}')
print(f'Infs in X_test: {np.isinf(X_test).sum()}')
print(f'Infs in y_test: {np.isinf(y_test).sum()}')

NaNs in X_train: 0
NaNs in y_train: 0
Infs in X_train: 0
Infs in y_train: 0
NaNs in X_test: 0
NaNs in y_test: 0
Infs in X_test: 0
Infs in y_test: 0


In [ ]:
X_train.shape

In [ ]:
X_test.shape

In [ ]:
y_train.shape

In [ ]:
y_test.shape

# implimented using ANN

In [3]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import TensorBoard 


log_dir = os.path.join("logs")
tb_callback = TensorBoard(log_dir=log_dir)

num_samples, dim1, dim2 = X_train.shape
X_train_flattened = X_train.reshape(num_samples, dim1 * dim2)


# Step 3: Define the ANN model
model = Sequential()
model.add(Dense(128, input_dim=dim1 * dim2, activation='relu'))   
model.add(Dense(64, activation='relu'))  
model.add(Dense(8, activation='softmax'))              

# Step 4: Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

# Step 5: Train the model
model.fit(X_train_flattened, y_train, epochs=500, batch_size=32,callbacks=[tb_callback])


Epoch 1/500
8/8 [==============================] - 1s 18ms/step - loss: 2.4910 - categorical_accuracy: 0.1719
Epoch 2/500
8/8 [==============================] - 0s 17ms/step - loss: 1.7957 - categorical_accuracy: 0.3594
Epoch 3/500
8/8 [==============================] - 0s 17ms/step - loss: 1.5659 - categorical_accuracy: 0.3711
Epoch 4/500
8/8 [==============================] - 0s 17ms/step - loss: 1.2841 - categorical_accuracy: 0.5273
Epoch 5/500
8/8 [==============================] - 0s 17ms/step - loss: 1.0430 - categorical_accuracy: 0.6992
Epoch 6/500
8/8 [==============================] - 0s 17ms/step - loss: 0.8713 - categorical_accuracy: 0.7891
Epoch 7/500
8/8 [==============================] - 0s 18ms/step - loss: 0.7371 - categorical_accuracy: 0.9180
Epoch 8/500
8/8 [==============================] - 0s 16ms/step - loss: 0.6291 - categorical_accuracy: 0.8984
Epoch 9/500
8/8 [==============================] - 0s 18ms/step - loss: 0.5229 - categorical_accuracy: 0.9023
Epoch 10/5

KeyboardInterrupt: 

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
# Make predictions on the test set
num_samples, dim1, dim2 = X_test.shape
X_test_flattened = X_test.reshape(num_samples, dim1 * dim2)
y_pred_prob = model.predict(X_test_flattened)
y_pred = np.argmax(y_pred_prob, axis=1)

# Convert y_test if one-hot encoded
if y_test.ndim > 1:
    y_test = np.argmax(y_test, axis=1)

#accuracy and loss
accuracy = accuracy_score(y_test, y_pred)
print('accuracy:')
print(accuracy)
# Generate the confusion matrix
print('confusion matrix:')
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Implimented using RNN

In [4]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
from tensorflow.keras.callbacks import TensorBoard
import os

# Define log directory for TensorBoard
log_dir = os.path.join("logs")
tb_callback = TensorBoard(log_dir=log_dir)

# Define the model
model = Sequential()
model.add(SimpleRNN(128, activation='relu', return_sequences=True, input_shape=(70, 111)))
model.add(SimpleRNN(64, activation='relu', return_sequences=True))
model.add(SimpleRNN(64, activation='relu', return_sequences=False))
model.add(Dense(32, activation='relu'))
model.add(Dense(8, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

# Fit the model
model.fit(X_train, y_train, epochs=1000, callbacks=[tb_callback])


Epoch 1/1000
8/8 [==============================] - 3s 28ms/step - loss: 2.1264 - categorical_accuracy: 0.1641
Epoch 2/1000
8/8 [==============================] - 0s 25ms/step - loss: 1.9840 - categorical_accuracy: 0.2070
Epoch 3/1000
8/8 [==============================] - 0s 25ms/step - loss: 1.8558 - categorical_accuracy: 0.4102
Epoch 4/1000
8/8 [==============================] - 0s 26ms/step - loss: 1.6146 - categorical_accuracy: 0.4531
Epoch 5/1000
8/8 [==============================] - 0s 26ms/step - loss: 1.3950 - categorical_accuracy: 0.4688
Epoch 6/1000
8/8 [==============================] - 0s 25ms/step - loss: 1.1232 - categorical_accuracy: 0.5703
Epoch 7/1000
8/8 [==============================] - 0s 28ms/step - loss: 0.8720 - categorical_accuracy: 0.6875
Epoch 8/1000
8/8 [==============================] - 0s 26ms/step - loss: 0.7896 - categorical_accuracy: 0.6758
Epoch 9/1000
8/8 [==============================] - 0s 27ms/step - loss: 0.5969 - categorical_accuracy: 0.7812
E

KeyboardInterrupt: 

In [5]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)

# Convert y_test if one-hot encoded
if y_test.ndim > 1:
    y_test = np.argmax(y_test, axis=1)

#accuracy and loss
accuracy = classification_report(y_test, y_pred)
print('classification report:')
print(accuracy)
# Generate the confusion matrix
print('confusion matrix:')
cm = confusion_matrix(y_test, y_pred)
print(cm)

2/2 [==============================] - 0s 11ms/step
classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11
           3       1.00      1.00      1.00         8
           4       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         8
           6       1.00      1.00      1.00         9
           7       1.00      1.00      1.00        10

    accuracy                           1.00        64
   macro avg       1.00      1.00      1.00        64
weighted avg       1.00      1.00      1.00        64

confusion matrix:
[[ 4  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0]
 [ 0  0  0  0  5  0  0  0]
 [ 0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0 10]]


In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 70, 128)           30720     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 70, 64)            12352     
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 64)                8256      
                                                                 
 dense (Dense)               (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 8)                 264       
                                                                 
Total params: 53672 (209.66 KB)
Trainable params: 53672 (209.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Implimented using LSTM

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard 


log_dir = os.path.join("logs")
tb_callback = TensorBoard(log_dir=log_dir)




model = Sequential()
model.add(LSTM(128, activation='relu', return_sequences=True, input_shape=(70, 111))) 
model.add(LSTM(128, activation='relu', return_sequences=True)) 
model.add(LSTM(64, activation='relu', return_sequences=False)) 
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(8, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

model.fit(X_train, y_train, epochs=1000, callbacks=[tb_callback])

In [6]:
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import LSTM, Dense
# from tensorflow.keras.callbacks import TensorBoard, Callback
# import os

# class EarlyStoppingByAccuracy(Callback):
#     def __init__(self, monitor='categorical_accuracy', value=0.99, verbose=1):
#         super(Callback, self).__init__()
#         self.monitor = monitor
#         self.value = value
#         self.verbose = verbose

#     def on_epoch_end(self, epoch, logs={}):
#         current = logs.get(self.monitor)
#         if current is None:
#             raise ValueError(f"Monitor '{self.monitor}' is not available in logs. Available keys are: {', '.join(logs.keys())}")
        
#         if current >= self.value:
#             if self.verbose > 0:
#                 print(f"\nEpoch {epoch + 1}: early stopping threshold of {self.value} reached. Stopping training.")
#             self.model.stop_training = True

# log_dir = os.path.join("logs")
# tb_callback = TensorBoard(log_dir=log_dir)

# model = Sequential()
# model.add(LSTM(128, activation='relu', return_sequences=True, input_shape=(70, 111))) 
# model.add(LSTM(128, activation='relu', return_sequences=True)) 
# model.add(LSTM(64, activation='relu', return_sequences=False)) 
# model.add(Dense(64, activation='relu'))
# model.add(Dense(32, activation='relu'))
# model.add(Dense(8, activation='softmax'))

# model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

# # Define the early stopping callback
# early_stopping_callback = EarlyStoppingByAccuracy(monitor='categorical_accuracy', value=0.99)

# model.fit(X_train, y_train, epochs=1000, callbacks=[tb_callback, early_stopping_callback])


Epoch 1/1000
8/8 [==============================] - 4s 96ms/step - loss: 2.1500 - categorical_accuracy: 0.1211
Epoch 2/1000
8/8 [==============================] - 1s 95ms/step - loss: 2.0423 - categorical_accuracy: 0.2109
Epoch 3/1000
8/8 [==============================] - 1s 94ms/step - loss: 2.0556 - categorical_accuracy: 0.1484
Epoch 4/1000
8/8 [==============================] - 1s 95ms/step - loss: 1.9656 - categorical_accuracy: 0.1875
Epoch 5/1000
8/8 [==============================] - 1s 93ms/step - loss: 1.8954 - categorical_accuracy: 0.2539
Epoch 6/1000
8/8 [==============================] - 1s 91ms/step - loss: 2.1007 - categorical_accuracy: 0.1641
Epoch 7/1000
8/8 [==============================] - 1s 93ms/step - loss: 4.8173 - categorical_accuracy: 0.0742
Epoch 8/1000
8/8 [==============================] - 1s 99ms/step - loss: 2.0602 - categorical_accuracy: 0.1602
Epoch 9/1000
8/8 [==============================] - 1s 91ms/step - loss: 2.0317 - categorical_accuracy: 0.2266
E

In [5]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
# Make predictions on the test set


y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)

# Convert y_test if one-hot encoded
if y_test.ndim > 1:
    y_test = np.argmax(y_test, axis=1)

#accuracy and loss
accuracy = accuracy_score(y_test, y_pred)
print('accuracy:')
print(accuracy)
# Generate the confusion matrix
print('confusion matrix:')
cm = confusion_matrix(y_test, y_pred)
print(cm)

2/2 [==============================] - 0s 3ms/step
accuracy:
0.984375
confusion matrix:
[[ 7  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  1]
 [ 0  0  7  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0]
 [ 0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  7  0  0]
 [ 0  0  0  0  0  0  8  0]
 [ 0  0  0  0  0  0  0 13]]


In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 70, 128)           122880    
                                                                 
 lstm_1 (LSTM)               (None, 70, 128)           131584    
                                                                 
 lstm_2 (LSTM)               (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 64)                4160      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 8)                 264       
                                                                 
Total params: 310376 (1.18 MB)
Trainable params: 310376 

In [6]:
#save the model
model.save('my_model3.keras')

In [13]:
import time
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.metrics import classification_report, confusion_matrix

# Load your pre-trained model
model = load_model('my_model2.keras')

data = pd.read_csv('keypoints\\come\\1.csv')

# Extract only the values as a numpy array
keypoints = data.values
keypoints = np.expand_dims(keypoints, axis=0)  # Expand dimensions to match the model input shape (1, 70, 111)
# Measure prediction time
start_time = time.time()
predictions = model.predict(keypoints)
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

print(f"Time taken to make predictions: {elapsed_time} seconds")




y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)

# Convert y_test if one-hot encoded
if y_test.ndim > 1:
    y_test = np.argmax(y_test, axis=1)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))



1/1 [==============================] - 0s 393ms/step
Time taken to make predictions: 0.4266395568847656 seconds
2/2 [==============================] - 0s 39ms/step
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       1.00      1.00      1.00        11
           2       0.92      1.00      0.96        11
           3       1.00      1.00      1.00        10
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         5
           6       1.00      1.00      1.00         6
           7       1.00      1.00      1.00         6

    accuracy                           0.98        64
   macro avg       0.99      0.99      0.99        64
weighted avg       0.99      0.98      0.98        64


Confusion Matrix:
[[ 8  0  1  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0]
 [ 0  0  0  0  6  0  0  0]
 [ 0  0 